dist: trusty
language: java
jdk:
  - openjdk11
  
sudo: false

addons:
  apt:
    packages:
      - tree

before_install:
  - rvm install 2.2.5
  - rvm use 2.2.5

script:
  - mvn test -f ./pom.xml
    
